### ISSUE TITLE
EPC / Products - do we need a name?

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/project-traceability#18]
The EPCIS and UN specifications only use an identifier for products.  but the blockchain platform allows a name - and doesnt demand an ID.  Should the API

1. remove the option for a name?
2. allow either a name or an ID or both (ie at least one)?
3. require an ID and allow an optional name?

**Comment by VladimirAlexiev** [comment]
IMHO you need ID because these are the basis of URN/URLs, to which you attach product info as triples.
If you don't have an ID, you'd need to use  a blank node, skolemized URL, or UUID URN (nearly just as bad).

**Comment by onthebreeze** [comment]
yes agreed.  Will make ID mandatory and product name optional.  In general, only IDs should be needed if we lived in a world where other metadata was always discoverable given an ID.  But we arent quite there yet so seems reasonable to leave product name in there as option
