### ISSUE TITLE
JSON-LD vocabulary representation of ITC harmonised sustainability criteria

### ISSUE THREAD

**Issue by onthebreeze** [uncefact/project-traceability#23]
The ITC has developed a standards map - see https://www.standardsmap.org/en/identify that maps over 300 sustainability standards to a harmonised vocabulary.  It would be very useful to have a JSON-LD vocabulary that represents the harmonised ITC vocabulary so that each unique standard could be mapped to the hamonised vocabulary via a JSON-LD context file.

Lets have a stab at making a first draft vocabulary using the data in the tab "ALL Criteria GLOSSARY JAN 2018" in the workbook "Sustainability Criteria Table_ITC_March2021.xslx" attached here.

[Sustainability Criteria Table_ITC_March2021.xlsx](https://github.com/uncefact/traceability/files/8804861/Sustainability.Criteria.Table_ITC_March2021.xlsx)

comments & questions welcome on this ticket regarding how best to map the data to JSON-LD/RDFS using similar architecture / principles to the vocabulary work at https://github.com/uncefact/vocab

**Comment by onthebreeze** [comment]
first draft JSON-LD version of ITC vocabulary is here https://github.com/uncefact/traceability/blob/main/vocabulary/itc_output.jsonld

@colugo - any chance you can have a go at a jargon import?

**Comment by colugo** [comment]
I had a look through this, but I don't think (or at least I don't understand how) I could construct an information model from it.

The context graph only contains things that look like this:

 {
            "@id": "itc:289",
            "@type": "itc:Recommendation",
            "rdfs:comment": "DESCRIPTION:\nDoes the standard include criteria on limitations of wastewater volumes?\n\nDEGREE OF INTENSITY:\n1 - Measure wastewater volumes\n2 - Monitor wastewater volumes over time\n3 - Limit wastewater volumes",
            "rdfs:label": "**Criteria relating to limitations of wastewater volume",
            "itc:subSection": "Environment",
            "itc:subSubSection": "WATER"
        }


My mental model was that each of these would represent a property, with some pointer to the entity it belongs to.
I could create domains from the subSections (Enironment, here) and classes from the subSubSections (WATER, here), but there is no name for the property.



My current jsonld importer likes things more like this (i'm talking about the information content, I'll make it work with whatever syntax is used):

{
@id: "unece:additionalStreetName",
@type: "rdf:Property",
schema:rangeIncludes: {
@id: "xsd:string"
},
schema:domainIncludes: {
@id: "unece:Address"
},
rdfs:comment: "The additional name of a street, expressed as text, for this trade address.",
rdfs:label: "additionalStreetName",
unece:cefactElementMetadata: [
{
@id: "cefact:Trade_Address.Additional_StreetName.Text",
@type: "unece:BasicBIE",
unece:cefactBieDomainClass: "cefact:Trade_Address.Details",
rdfs:comment: "The additional name of a street, expressed as text, for this trade address."
}
]
},

**Comment by onthebreeze** [comment]
It’s more like a taxonomy - ie a hierarchical code list.  So I suppose it’s really a graph not an ER

How best to represent in jargon? A hierarchy of classes ?

Steven Capell
Mob: 0410 437854

**Comment by colugo** [comment]
Here's an example

https://jargon.sh/user/jargon/ITC_example/editor#

You could have everything in one monolithic domain (like the above example), or each entity (blue box) could be it's own domain.

My above comment was more around the naming of the properties. Is 'itc:xxx' really the authoritative name, or is there a more human-friendly short name.

For example. The description for itc:437 has a description of "Does the standard have processes in place for maintaining access to livelihoods for surrounding communities".

So instead of a Jargon model of

HumanRigthsAndLocalCommunities
  itc437:Text

I would rather have

HumanRightsAndLocalCommunities
  communityLivelihood:Text // with a description containing [itc.id]=itc437

**Comment by onthebreeze** [comment]
yes ok, well first go is always an experiment that teaches us what to change.  @kshychko how about we have a second go which aims for an output more like this:

## Vocabulary Files

One json-ld graph for each "Domain" in the spreadsheet.  Note there are currently only two.  One more coming.

## Classes

Generate one of these for every class / sub-class / sub-subclass in the attached spreadsheet.

```
{
   @id: "itc:Environment.Soil",
   @type: "rdfs:Class",
   rdfs:comment: "General principle on soil management, as described in the standard",
   rdfs:label: "Environment - Soil"
   itc:ElementMetadata: [
      {
        itc:internalNodeID: "2053",
        itc:NodeID: "B.2.a"
      }
   ]
}
```

## Properties

Generate one of these for every Property in the attached sheet

```
{
   @id: "itc:forests.FMP_annual_allowable_cut",
   @type: "rdf:Property",
   schema:rangeIncludes: {
        @id: "xsd:boolean"
        },
    schema:domainIncludes: [
        {
        @id: "itc:environment.forests"
        }
    ],
   rdfs:comment: "The forest management plan defines the annual allowable cut.Does the standard require that the forest management plan defines the annual allowable cut?",
   rdfs:label: "FMP annual allowable cut",
   itc:ElementMetadata: [
      {
        itc:internalNodeID: "700339",
        itc:nodeID: "B.2.b.12",
        itc:guidance: "The annual allowable cut refers to a defined rate of extraction of timber.Provide evidence (criterion number and URL) that the standard requires the forest management plan to define the annual allowable cut",
        itc:originalPropertyName:"Criteria related to FMP annual allowable cut"
      }
   ]
}
```

## Code Lists

And one of these for every enumeration.  Note that there is an enumeration for very property of type "code" in the spreadsheet and the value are either

* Listed in rows directly under the words 'Enumerated below" in the range column (J) - or -
* listed as number separated strings in the "Degree of Intensity" column M

```
Not actually sure how best to represent the codes - but I dont think we want a seaprate vocabulary files for each codelist - they should be part of the single domain vocabulary.

[Sustainability Criteria Table_ITC_Cleaned.xlsx](https://github.com/uncefact/traceability/files/8839724/Sustainability.Criteria.Table_ITC_Cleaned.xlsx)

**Comment by onthebreeze** [comment]
when you make the property IDs - just take the test string in the "property" column of the spreadsheet and turn it into an @id by

* removing any leading spaces and any punctuation.
* converting all words to lower case
* concatenating words as snake case - ie with the "_" underscore delimiter.
* prefix with the class name followed by "." (which should be the only "." once punctuation is removed in the first step)

I've gone through and had a first pass at making the strings shorter - but it'll need a much more careful second pass at some point to make meaningful but short names for every property.

I've also put the original string from ITC in the elementMetadata structure so we dont lose it...

**Comment by Fak3** [comment]
>> @id: "itc:Environment.Soil"

 Without url escaping, dots may be problematic for some url parsers. Maybe use ''-" as separator?

**Comment by kshychko** [comment]
> > > @id: "itc:Environment.Soil"
> 
> Without url escaping, dots may be problematic for some url parsers. Maybe use ''-" as separator?

@onthebreeze , do we need the "prefix" if it will be a part of the URL?
http://standardsmap.org/requirements/environment/soil/quality

**Comment by onthebreeze** [comment]
Not necessarily.  Don’t treat my json-ld snippets as hard requirements , rather as guidance.  Just do what you think is right.  No doubt there will be another iteration anyway

**Comment by onthebreeze** [comment]
Next version of the vocabulary available here https://github.com/uncefact/traceability/blob/main/vocabulary/itc_output_2022_06_08.jsonld

**Comment by onthebreeze** [comment]
this task has reached "good enough for now" level - see https://github.com/uncefact/project-traceability/tree/main/vocabulary and https://jargon.sh/user/unece/sustainability_vocab/v/working/artefacts/specification/render - will be closed now

**Comment by VladimirAlexiev** [comment]
@Fak3 
> Without url escaping, dots may be problematic for some url parsers. Maybe use ''-" as separator?

That has not been true for some 10 years, since FreeBase started using dotted properties. It's allowed in Turtle 1.1 and SPARQL 1.1 and everyone supports it.

**Comment by VladimirAlexiev** [comment]
@Fak3 Hi Roman, how to contact you? Can't find you on twitter, linkedin...

**Comment by Fak3** [comment]
> @Fak3 Hi Roman, how to contact you? Can't find you on twitter, linkedin...

It is best to reach me via email someuniquename@gmail.com
